name: Go BUILD

on:
  workflow_run:
    workflows: ["Go CI"]
    types:
      - completed
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build
        run: go build main.go

      - name: Upload Compiled Project
        uses: actions/upload-artifact@v4
        with:
          name: compiled-project
          path: main
